### ISSUE TITLE
Better error reporting if worker dies

### ISSUE THREAD

**Issue by kelunik** [amphp/parallel#13]
https://github.com/amphp/parallel/commit/4546ef8b1dff8fb291014c046f4839e799582983 reports the header now, I'm not sure whether it's safe to just use `": " . $header . yield` there to provide more debugging info.

**Comment by trowski** [comment]
Further improved in https://github.com/amphp/parallel/commit/20bb51e926b01b42da52c320da5d37971f0067f5.

It might be safe to do add `\bin2hex($header . yield)`. There is a possibility there that would hang waiting for more data that never arrives.

Should there be more verification than just a leading null byte? I initially added the null byte because the message length was later passed to `fread`, which would fail with a memory error if the length was invalid and very large.

**Comment by kelunik** [comment]
I think a leading NUL byte already catches all fatal errors.

**Comment by kelunik** [comment]
I think this is good enough now with forwarding all errors to the parents stderr.
