### ISSUE TITLE
Fatal error: Uncaught Error: Could not locate PHP executable binary in C:\laragon\www\doodle\vendor\amphp\parallel\lib\Context\Process.php

### ISSUE THREAD

**Issue by chegmarco1989** [amphp/parallel#148]
Hi.

I get the following errors:

`Fatal error: Uncaught Error: Could not locate PHP executable binary in C:\laragon\www\doodle\vendor\amphp\parallel\lib\Context\Process.php:163 Stack trace: #0 C:\laragon\www\doodle\vendor\amphp\parallel\lib\Context\Process.php(87): Amp\Parallel\Context\Process::locateBinary() #1 C:\laragon\www\doodle\vendor\amphp\parallel\lib\Worker\Internal\WorkerProcess.php(18): Amp\Parallel\Context\Process->__construct(Array, NULL, Array, NULL) #2 C:\laragon\www\doodle\vendor\amphp\parallel\lib\Worker\WorkerProcess.php(37): Amp\Parallel\Worker\Internal\WorkerProcess->__construct(Array, Array, NULL) #3 C:\laragon\www\doodle\vendor\amphp\parallel\lib\Worker\DefaultWorkerFactory.php(58): Amp\Parallel\Worker\WorkerProcess->__construct('Amp\\Parallel\\Wo...', Array, NULL) #4 C:\laragon\www\doodle\vendor\amphp\parallel\lib\Worker\DefaultPool.php(227): Amp\Parallel\Worker\DefaultWorkerFactory->create() #5 C:\laragon\www\doodle\vendor\amphp\parallel\lib\Worker\DefaultPool.php(151): Amp\Parallel\Worker\DefaultPool->pull() #6 C:\laragon\www\dood in C:\laragon\www\doodle\vendor\amphp\parallel\lib\Context\Process.php on line 163`

Any help ???

**Comment by trowski** [comment]
Apologies that this issue did not receive more immediate attention.

The process runner attempts to locate the PHP binary at a number of expected locations. If it is unable to because you've installed PHP at a different location, you may have to manually pass the path to the `Process` context constructor.

Seeing as this issue is old, I'm going to close it. If you need further support, please open another issue (and I'll try to reply a bit faster) 👍
