### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by jigarius** [amphp/parallel#150]
It'd be great to have one example for each of the components of the library. For example, a basic usage example is on the README. It'd be good to have examples of:
- A custom `Worker` implementation.
- A custom `Task` implementation.
- A custom `Worker` implementation.

**Comment by gidzr** [comment]
I second that - but more specifically I'm struggling with the existing examples on two accounts:

1. I can't tell what amphp is doing any differently to running the same functions without amphp.. which I need to do, in order to ensure I've got everything set up correctly.
eg. I am running the script here: https://amphp.org/amp/event-loop/, and I see the output. However, when I run it, the tick tick tick appears all at once at the end of the script. I suspect I'm supposed to see a tick, then a delay of a second, then another tick, etc. So I'm pretty sure something's not working correctly. I've also setup timers, and there's no performance changes to whether I use the event-loop or run the same loop using sleep().
With the current documentation, it still feels like a black box.

2. Many of the examples for me are not easily translatable to application. I don't think this is due to a lack of real world examples. On the contrary, I prefer more 'hello world' examples, as this allows me to copy paste, test, then build out. \

The biggest issue is that I can't start my learning curve because I can't easily break things into basic functions, which I can test, and compare with what happens with amphp vs what happens without amphp. 

Maybe examples of BEFORE using amphp vs AFTER with amphp, in your example scripts using common functions like hello worlds and loops would be great, with clear expected behaviours if it's working vs not working.

Cheers

**Comment by kelunik** [comment]
I've added an example for a `Task` implementation now. There's usually no need to implement the `Worker` interface yourself.
