### ISSUE TITLE
How to cancel task by timeout

### ISSUE THREAD

**Issue by Ekstazi** [amphp/parallel#62]
Hi. How can i cancel task by timeout ?
Currently i use this way:
```
			$worker = $this->pool->getWorker();
			$promise = $worker->enqueue(new Executor($job));
			$token = new TimeoutCancellationToken(60000);
			$token->subscribe([$worker, 'cancel']);
```
Will it work as exoected ?

**Comment by trowski** [comment]
There is no method `Worker::cancel()`. The only way to forcibly cancel a task enqueued to a work is to kill the worker. This is because the task may be executing blocking code, rending the worker unresponsive while blocked. It looks like in #63 you realized this, but we need to fix killing a process that is currently blocked in `amphp/process`.
