### ISSUE TITLE
TaskFailure should send the original exception

### ISSUE THREAD

**Issue by mohamednagy** [amphp/parallel#76]
Hello,
[here](https://github.com/amphp/parallel/blob/master/lib/Worker/Internal/TaskFailure.php#L38) you convert the original exception to `TaskException` or `TaskError`, is there any reason for that. because i have a case that i need the original exception but because it's being converted so i don't have access to that exception, i think it would be better to throw the original exceptions

**Comment by kelunik** [comment]
It's not possible, because exceptions can't be serialized.

**Comment by romm** [comment]
Hey there, sorry for the bump.

I was also wondering how to get back the original exception sent from a `\Amp\Parallel\Worker\Task`, and the search lead me here. I'm probably missing something, but in which cases exceptions can't be serialized? The following snippet seems to show it is possible to serialize them (at least in simple cases): https://3v4l.org/BUGJW

Thank you for your work! 😊

**Comment by trowski** [comment]
Exceptions are not always serializable because the stack-trace contains references to function/method arguments and objects which may not be serializable. This is why the back-trace contained in the data sent to the parent has been altered to remove these potentially unserializable values.

Exception handling from contexts and tasks should be _exceptional_, not the norm. Do not design your contexts and tasks to throw exceptions, rather return meaningful results, even if those results are errors.
